apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: production
  labels:
    app: auth-service
    component: backend
    part-of: task-management
    version: v1
    managed-by: kubectl
    tier: backend
    environment: production
    security-tier: critical
  annotations:
    # Prometheus monitoring configuration
    prometheus.io/scrape: "true"
    prometheus.io/port: "3001"
    prometheus.io/path: "/metrics"
    
    # AWS load balancer configuration
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    
    # Service mesh configuration
    service.istio.io/canonical-name: auth-service
    service.istio.io/canonical-revision: v1
    
    # Security annotations
    security.alpha.kubernetes.io/pod-security-policy: restricted
    security.alpha.kubernetes.io/unsafe-sysctls: "none"
    
    # Documentation
    description: "Authentication service for task management system"
    owner: "platform-team"

spec:
  type: ClusterIP
  selector:
    app: auth-service
    component: backend
    version: v1
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
    - name: http-monitoring
      protocol: TCP
      port: 15014
      targetPort: 15014
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  sessionAffinity: None
  publishNotReadyAddresses: false
  
  # Enhanced service configuration
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4