apiVersion: v1
kind: ConfigMap
metadata:
  name: file-service-config
  namespace: ${NAMESPACE}
  labels:
    app: file-service
    component: config
data:
  # Core service configuration
  PORT: "3000"
  NODE_ENV: "${NODE_ENV}"
  SERVICE_NAME: "file-service"
  VERSION: "1.0.0"

  # Storage configuration
  STORAGE_PROVIDER: "s3"  # Supports 's3' or 'local'
  STORAGE_BUCKET: "task-management-files-${NODE_ENV}"
  AWS_REGION: "us-west-2"  # Default region, override per environment

  # Security settings
  CORS_ORIGIN: "https://*.taskmanagement.com"
  ENCRYPTION_ENABLED: "true"
  ENCRYPTION_ALGORITHM: "AES-256"

  # File upload constraints
  MAX_FILE_SIZE: "10485760"  # 10MB in bytes
  ALLOWED_FILE_TYPES: "image/jpeg,image/png,image/gif,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain"

  # Performance tuning
  UPLOAD_CHUNK_SIZE: "1048576"  # 1MB chunks for multipart uploads
  MAX_CONCURRENT_UPLOADS: "3"
  UPLOAD_TIMEOUT: "300000"  # 5 minutes in milliseconds

  # Environment-specific overrides
  development:
    CORS_ORIGIN: "http://localhost:*"
    ENCRYPTION_ENABLED: "false"
    MAX_FILE_SIZE: "20971520"  # 20MB for development
    
  staging:
    STORAGE_BUCKET: "task-management-files-staging"
    ENCRYPTION_ALGORITHM: "AES-256-CBC"
    
  production:
    STORAGE_BUCKET: "task-management-files-prod"
    ENCRYPTION_ALGORITHM: "AES-256-GCM"
    MAX_CONCURRENT_UPLOADS: "5"
    CORS_ORIGIN: "https://*.taskmanagement.com"
    
  # Monitoring and logging
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"

  # Health check configuration
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_PORT: "8080"
  READINESS_TIMEOUT: "5000"
  LIVENESS_TIMEOUT: "3000"