apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: default
  labels:
    app: notification-service
    component: config
data:
  # Core Notification Service Settings
  NOTIFICATION_SERVICE_ENABLED: "true"
  LOG_LEVEL: "info"

  # WebSocket Configuration
  WEBSOCKET_ENABLED: "true"
  WEBSOCKET_PORT: "3002"
  WEBSOCKET_PATH: "/ws"
  WEBSOCKET_SSL_ENABLED: "true"
  WEBSOCKET_MAX_CONNECTIONS: "10000"
  WEBSOCKET_PING_INTERVAL: "25000"
  WEBSOCKET_PING_TIMEOUT: "5000"

  # Email Delivery Configuration
  EMAIL_ENABLED: "true"
  EMAIL_PROVIDER: "sendgrid"
  EMAIL_TEMPLATE_PATH: "/etc/taskmanager/notification-templates"
  
  # Push Notification Configuration
  PUSH_NOTIFICATION_ENABLED: "false"
  PUSH_NOTIFICATION_PLATFORM: "firebase"

  # Rate Limiting Settings
  RATE_LIMIT_PER_MINUTE: "60"
  RATE_LIMIT_PER_HOUR: "1000"
  RATE_LIMIT_PER_USER_MINUTE: "100"
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX_REQUESTS: "1000"

  # Retry Policy Configuration
  RETRY_MAX_ATTEMPTS: "3"
  RETRY_BACKOFF_MS: "1000"
  RETRY_MAX_BACKOFF_MS: "30000"
  RETRY_JITTER_MS: "100"

  # Batch Processing Settings
  BATCH_PROCESSING_ENABLED: "true"
  BATCH_SIZE: "100"
  BATCH_INTERVAL_MS: "5000"
  BATCH_MAX_RETRIES: "3"

  # Template Configuration
  DEFAULT_LOCALE: "en"
  SUPPORTED_LOCALES: "en,es,fr"
  TEMPLATE_CACHE_TIMEOUT: "3600000"

  # CORS Configuration
  CORS_ORIGINS: "https://taskmanager.com"
  CORS_METHODS: "GET,POST"
  CORS_HEADERS: "Authorization,Content-Type,X-Requested-With,X-Socket-ID"
  CORS_MAX_AGE: "86400"

  # Security Settings
  SSL_ENABLED: "true"
  SSL_KEY_PATH: "/etc/ssl/private/notification-service.key"
  SSL_CERT_PATH: "/etc/ssl/certs/notification-service.crt"

  # Monitoring Configuration
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  TRACING_ENABLED: "true"
  TRACING_SAMPLING_RATE: "0.1"

  # Environment-specific Settings
  NODE_ENV: "production"
  SERVICE_NAME: "notification-service"
  VERSION: "1.0.0"