apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: production
  labels:
    app: notification-service
    component: backend
    part-of: task-management
    version: v1
    tier: application
  annotations:
    # Monitoring configuration
    prometheus.io/scrape: "true"
    prometheus.io/port: "3003"
    prometheus.io/path: "/metrics"
    
    # Service mesh configuration
    service.istio.io/canonical-name: "notification-service"
    service.istio.io/canonical-revision: "v1"
    security.istio.io/tlsMode: "strict"
    sidecar.istio.io/inject: "true"

spec:
  type: ClusterIP
  ports:
    # HTTP port for REST API and metrics
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: http
      appProtocol: http
    
    # WebSocket port for real-time notifications
    - port: 3004
      targetPort: 3004
      protocol: TCP
      name: websocket
      appProtocol: ws
  
  # Pod selector based on deployment labels
  selector:
    app: notification-service
    component: backend
  
  # Session affinity configuration for WebSocket connections
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hour timeout
  
  # Topology configuration for high availability
  publishNotReadyAddresses: false
  topologyKeys:
    - "kubernetes.io/hostname"
    - "topology.kubernetes.io/zone"
    - "topology.kubernetes.io/region"
    - "*"