apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-config
  namespace: production
  labels:
    app: task-service
    component: config
    environment: production
data:
  # Core Application Settings
  NODE_ENV: "production"
  SERVICE_NAME: "task-service"
  PORT: "3000"
  LOG_LEVEL: "info"

  # Database Configuration
  DATABASE_HOST: "postgres-rw.database"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "taskdb"
  DATABASE_USER: "task_service"
  DATABASE_SSL: "true"
  DATABASE_MIN_POOL: "10"
  DATABASE_MAX_POOL: "50"
  DATABASE_IDLE_TIMEOUT: "10000"
  DATABASE_CONNECTION_TIMEOUT: "3000"
  DATABASE_STATEMENT_TIMEOUT: "5000"
  DATABASE_QUERY_TIMEOUT: "3000"

  # Redis Cache Configuration
  REDIS_HOST: "redis-master.cache"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_TTL: "300"
  REDIS_RETRY_ATTEMPTS: "3"
  REDIS_RETRY_DELAY: "1000"
  REDIS_CLUSTER_MODE: "true"

  # Task Management Limits
  MAX_TASKS_PER_PAGE: "100"
  MAX_TITLE_LENGTH: "200"
  MAX_DESCRIPTION_LENGTH: "5000"
  MAX_TAGS_PER_TASK: "10"
  MAX_ATTACHMENTS_PER_TASK: "20"
  MAX_COMMENT_LENGTH: "1000"
  MAX_COMMENTS_PER_TASK: "100"

  # Task Status and Priority Configuration
  DEFAULT_TASK_STATUS: "TODO"
  DEFAULT_TASK_PRIORITY: "MEDIUM"
  VALID_TASK_STATUSES: "TODO,IN_PROGRESS,REVIEW,DONE"
  VALID_TASK_PRIORITIES: "LOW,MEDIUM,HIGH,URGENT"

  # Cache Strategy Configuration
  ENABLE_CACHE: "true"
  CACHE_TTL: "300"
  CACHE_STRATEGY: "write-through"
  CACHE_INVALIDATION_PATTERN: "task:*"

  # Monitoring and Metrics
  METRICS_ENABLED: "true"
  METRICS_INTERVAL: "15000"
  METRICS_PREFIX: "task_service"
  TRACING_ENABLED: "true"
  TRACING_SAMPLE_RATE: "0.1"

  # API Configuration
  API_TIMEOUT: "5000"
  API_RETRY_ATTEMPTS: "3"
  API_RETRY_DELAY: "1000"

  # Rate Limiting
  RATE_LIMIT_WINDOW: "60000"
  RATE_LIMIT_MAX_REQUESTS: "1000"
  RATE_LIMIT_STRATEGY: "sliding-window"

  # CORS Configuration
  CORS_ALLOWED_ORIGINS: "https://*.example.com"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,PATCH"
  CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
  CORS_MAX_AGE: "86400"

  # Service Integration
  NOTIFICATION_SERVICE_URL: "http://notification-service:3000"
  NOTIFICATION_RETRY_ATTEMPTS: "3"

  # WebSocket Configuration
  WEBSOCKET_ENABLED: "true"
  WEBSOCKET_PATH: "/ws"
  WEBSOCKET_MAX_CONNECTIONS: "10000"

  # Audit Configuration
  AUDIT_ENABLED: "true"
  AUDIT_LOG_LEVEL: "info"
  AUDIT_RETENTION_DAYS: "90"