apiVersion: v1
kind: ConfigMap
metadata:
  name: project-service-config
  namespace: production
  labels:
    app: project-service
    tier: backend
    environment: production
    part-of: task-management-system
  annotations:
    description: "Production configuration for Project Service"
    version: "1.0.0"
    last-updated: "2024-01-20"
    maintainer: "platform-team"
data:
  # Application Configuration
  APP_ENV: "production"
  APP_PORT: "3000"

  # Database Configuration
  DB_HOST: "project-db.production.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "project_db"
  DB_POOL_MIN: "5"
  DB_POOL_MAX: "20"
  DB_IDLE_TIMEOUT: "10000"
  DB_CONNECTION_TIMEOUT: "3000"

  # Redis Cache Configuration
  REDIS_HOST: "redis.production.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_TTL: "3600"
  REDIS_MAX_CONNECTIONS: "50"
  REDIS_CONNECT_TIMEOUT: "3000"

  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  LOG_RETENTION_DAYS: "30"

  # Project Service Specific Settings
  MAX_PROJECTS_PER_ORG: "1000"
  PROJECT_CACHE_TTL: "300"
  PROJECT_BATCH_SIZE: "100"

  # Monitoring and Health Check
  METRICS_PORT: "9090"
  METRICS_PATH: "/metrics"
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_INTERVAL: "30"

  # API Configuration
  API_RATE_LIMIT: "100"
  API_RATE_WINDOW: "60000"
  API_TIMEOUT: "5000"
  API_MAX_PAYLOAD_SIZE: "5mb"

  # CORS Configuration
  CORS_ALLOWED_ORIGINS: "https://*.example.com"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,PATCH"

  # Tracing and Error Handling
  TRACE_SAMPLE_RATE: "0.1"
  ERROR_RETRIES: "3"
  RETRY_BACKOFF: "1000"