apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: project-service-hpa
  namespace: production
  labels:
    app: project-service
    tier: backend
    environment: production
    version: v1
    part-of: task-management-system
  annotations:
    autoscaling.alpha.kubernetes.io/behavior: scale-up-stabilization-window=3m,scale-down-stabilization-window=10m
    description: "HPA configuration for Project Service with advanced scaling policies"
    last-updated: "2024-01-20"
    maintainer: "platform-team"

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 180  # 3 minutes stabilization window
      policies:
        - type: Pods
          value: 2  # Add up to 2 pods at a time
          periodSeconds: 60
        - type: Percent
          value: 50  # Or scale up by 50% of current pods
          periodSeconds: 60
      selectPolicy: Max  # Use the policy that results in the highest change

    scaleDown:
      stabilizationWindowSeconds: 600  # 10 minutes stabilization window
      policies:
        - type: Pods
          value: 1  # Remove 1 pod at a time
          periodSeconds: 60
        - type: Percent
          value: 20  # Or scale down by 20% of current pods
          periodSeconds: 60
      selectPolicy: Min  # Use the policy that results in the smallest change