apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: production
  labels:
    app: project-service
    tier: backend
    environment: production
    version: v1
    part-of: task-management-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
    service.istio.io/canonical-name: "project-service"
    service.istio.io/canonical-revision: "v1"
    sidecar.istio.io/inject: "true"

spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
      appProtocol: http
    - name: grpc
      port: 9090
      targetPort: grpc
      protocol: TCP
      appProtocol: grpc
  selector:
    app: project-service
    tier: backend
  sessionAffinity: None
  publishNotReadyAddresses: false
  topologyKeys:
    - "kubernetes.io/hostname"
    - "topology.kubernetes.io/zone"
    - "topology.kubernetes.io/region"
    - "*"