apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  labels:
    app: grafana
    component: monitoring
    environment: production
data:
  grafana.ini: |
    [server]
    protocol = https
    http_port = 3000
    domain = grafana.local
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    cert_file = /etc/grafana/certs/tls.crt
    cert_key = /etc/grafana/certs/tls.key

    [security]
    admin_user = ${GF_SECURITY_ADMIN_USER}
    admin_password = ${GF_SECURITY_ADMIN_PASSWORD}
    allow_embedding = true
    cookie_secure = true
    strict_transport_security = true
    content_security_policy = true

    [auth.anonymous]
    enabled = false

    [auth.basic]
    enabled = true

    [dashboards]
    default_home_dashboard_path = /etc/grafana/dashboards/overview.json
    versions_to_keep = 20
    min_refresh_interval = 10s

    [alerting]
    enabled = true
    execute_alerts = true
    error_or_timeout = alerting
    evaluation_timeout_seconds = 30
    notification_timeout_seconds = 30

  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"
          queryTimeout: "30s"
          httpMethod: "POST"
          manageAlerts: true
          alertmanagerUid: "alertmanager"
        secureJsonData:
          httpHeaderValue1: "${PROMETHEUS_API_KEY}"

  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: "Task Management System"
        folder: "Task Management"
        type: file
        disableDeletion: true
        updateIntervalSeconds: 30
        allowUiUpdates: false
        options:
          path: /etc/grafana/dashboards
          foldersFromFilesStructure: true