# ServiceAccount definitions for Task Management System microservices
# Version: v1
# Purpose: Define service identities with comprehensive security controls and service mesh integration

---
# API Gateway Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: production
  labels:
    app: task-management-system
    component: api-gateway
    tier: backend
    environment: production
    managed-by: kubernetes
    security-tier: critical
  annotations:
    kubernetes.io/service-account.name: api-gateway
    istio.io/inject: "true"
    security.istio.io/tlsMode: strict
    prometheus.io/scrape: "true"
    vault.hashicorp.com/agent-inject: "true"
    policy.otomi.io/backup: "true"

---
# Authentication Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: production
  labels:
    app: task-management-system
    component: auth-service
    tier: backend
    environment: production
    managed-by: kubernetes
    security-tier: critical
  annotations:
    kubernetes.io/service-account.name: auth-service
    istio.io/inject: "true"
    security.istio.io/tlsMode: strict
    prometheus.io/scrape: "true"
    vault.hashicorp.com/agent-inject: "true"
    policy.otomi.io/backup: "true"

---
# Task Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-service
  namespace: production
  labels:
    app: task-management-system
    component: task-service
    tier: backend
    environment: production
    managed-by: kubernetes
    security-tier: standard
  annotations:
    kubernetes.io/service-account.name: task-service
    istio.io/inject: "true"
    security.istio.io/tlsMode: strict
    prometheus.io/scrape: "true"
    vault.hashicorp.com/agent-inject: "true"
    policy.otomi.io/backup: "true"

---
# Project Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-service
  namespace: production
  labels:
    app: task-management-system
    component: project-service
    tier: backend
    environment: production
    managed-by: kubernetes
    security-tier: standard
  annotations:
    kubernetes.io/service-account.name: project-service
    istio.io/inject: "true"
    security.istio.io/tlsMode: strict
    prometheus.io/scrape: "true"
    vault.hashicorp.com/agent-inject: "true"
    policy.otomi.io/backup: "true"

---
# Notification Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: production
  labels:
    app: task-management-system
    component: notification-service
    tier: backend
    environment: production
    managed-by: kubernetes
    security-tier: standard
  annotations:
    kubernetes.io/service-account.name: notification-service
    istio.io/inject: "true"
    security.istio.io/tlsMode: strict
    prometheus.io/scrape: "true"
    vault.hashicorp.com/agent-inject: "true"
    policy.otomi.io/backup: "true"

---
# File Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-service
  namespace: production
  labels:
    app: task-management-system
    component: file-service
    tier: backend
    environment: production
    managed-by: kubernetes
    security-tier: standard
  annotations:
    kubernetes.io/service-account.name: file-service
    istio.io/inject: "true"
    security.istio.io/tlsMode: strict
    prometheus.io/scrape: "true"
    vault.hashicorp.com/agent-inject: "true"
    policy.otomi.io/backup: "true"