apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web
  namespace: production
  labels:
    app: task-management
    component: web
    environment: production
annotations:
    description: "HPA configuration for web frontend"
    last-updated: "2024-01-01"

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web

  # Minimum 2 replicas for high availability
  minReplicas: 2
  # Maximum 10 replicas based on scalability design
  maxReplicas: 10

  # Scaling metrics based on CPU and memory thresholds
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # Scale at 70% CPU utilization per technical requirements
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          # Scale at 80% memory utilization per technical requirements
          averageUtilization: 80

  # Scaling behavior configuration for production stability
  behavior:
    scaleUp:
      # 1-minute stabilization window for scale up
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2  # Add max 2 pods at a time
        periodSeconds: 60
    
    scaleDown:
      # 5-minute stabilization window for scale down to prevent thrashing
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1  # Remove only 1 pod at a time
        periodSeconds: 60